# Generated by Django 4.2.3 on 2025-03-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extrato', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valores',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
