# Generated by Django 4.2.3 on 2023-07-13 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0002_conta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conta',
            old_name='apelido',
            new_name='nome',
        ),
    ]
